"""Create a lightweight LangChain-style pipeline using composable Python callables."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable


@dataclass
class ChainStep:
    """One transformation in a processing chain."""

    name: str
    func: Callable[[str], str]

    def __call__(self, value: str) -> str:
        return self.func(value)


class SimpleChain:
    """Sequentially applies registered chain steps."""

    def __init__(self, steps: list[ChainStep]) -> None:
        self.steps = steps

    def run(self, prompt: str) -> str:
        value = prompt
        for step in self.steps:
            value = step(value)
        return value


def build_chain() -> SimpleChain:
    steps = [
        ChainStep("sanitize", lambda text: " ".join(text.strip().split())),
        ChainStep("extract_topic", lambda text: text.split(":", 1)[-1].strip()),
        ChainStep("summarize", lambda text: f"Summary: {text[:60]}"),
        ChainStep("finalize", lambda text: text + " [generated by SimpleChain]"),
    ]
    return SimpleChain(steps)


def main() -> None:
    chain = build_chain()
    prompt = "Task: Explain why caching helps API response times in backend systems."
    result = chain.run(prompt)

    print("Input prompt:")
    print(prompt)
    print("\nChain output:")
    print(result)


if __name__ == "__main__":
    main()
